### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by OJFord** [nicjo814/docker-baseimage-xenial-x#2]
How should audio work here? It's not working for me out of the box, using your `docker-plexmediaplayer` derivative (thanks, by the way!) - and I've tried:

- Mounting `/dev/snd` for alsa
- Mounting `/dev/shm` and other stuff for pulseaudio
- Mounting a socket and using `PULSE_SERVER`

all without success. But the readme here makes no mention of any of these, and yet says audio works.

Has something changed in docker perhaps, or is there something else I need to do to get it working? Many thanks.

**Comment by nicjo814** [comment]
I have only gotten sound to work if I pass the --privileged flag at startup. Alsa should work then if configured properly based on your sound card. In the https://github.com/nicjo814/docker-kodi image sound works "out of the box" when the proper soundcard is selected within Kodi (Alsa) and the same should be true for PMP I think.

**Comment by nicjo814** [comment]
Update: Just tested on an Ubuntu 17.04 and PMP did get audio without any modifications from me (just fired up the PMP container and started a video clip and audio worked)... I only used the privileged flag when starting the container.

**Comment by OJFord** [comment]
Hm, curious - I am using `privileged` as specified - I assumed it was needed for X; the potential for a problem with audio hadn't ocurred to me to until it happened!

I'll have another play - I tested that sound is actually working on the host (fresh install, arch) and Firefox played fine through pulseaudio. I don't know much about audio on Linux, but I gather pulse is just a layer on top of alsa, but perhaps the default settings somehow expect everything to come through pulseaudio - I gather if alsa is used directly, one application takes full control at a time, so perhaps that's sometimes a desirable setting.

Thanks for getting back to me, it's helpful to know it can work as-is, so just a host problem. Feel free to close this, or otherwise I'll close it when I have a fix to share.

**Comment by nicjo814** [comment]
Just a thought. Have you tried to run PMP in "TV mode"? There is a button for this on the top of the "Home" page of the web app. In TV mode it's possible to set which sound card to use under the Audio settings. I had to do this when I wanted to use digital passthrough via HDMI from PMP.

**Comment by OJFord** [comment]
Aha! That may well be it! I put it into TV mode for a bit just playing around, but I don't _think_ I had it that way when I was actually playing something, hoping for audio. I'll give that a go thanks!

> I had to do this when I wanted to use digital passthrough via HDMI from PMP.

... which is exactly what I'm trying to do (it being the only audio output connected) - I did change this in pavucontrol to get Firefox to work, but I couldn't find any such settings in PMP. It didn't occur to me that they might be hidden when not in 'TV mode'... 🙄

**Comment by nicjo814** [comment]
If you are using a Nvidia card you will probably have a number of "devices" listed in pmp that look very much the same. However only one of them will produce output over hdmi. It's a trial and error process...
